### ISSUE TITLE
Inference time

### ISSUE THREAD

**Issue by trungpham2606** [Scalsol/RepPointsV2#11]
Dear @Scalsol ,

Can you provide the inference time you get for 1 image ?

In my PC, the time is so slow.

**Comment by Scalsol** [comment]
On a Titan XP with R50 backbone, speed of reppoints v1 is about 13img/s, reppoints v2 is about 9img/s, but if you are using the dense reppoints then the speed will be very slow and authors of this paper are still optimizing their code to accelerate it.

**Comment by trungpham2606** [comment]
@Scalsol 
Thank you for your prompt response.
