### ISSUE TITLE
The code implementation of verification tasks 

### ISSUE THREAD

**Issue by gp12345678** [Scalsol/RepPointsV2#3]
请问RepPointsV2中验证任务的实现代码实现在哪？

**Comment by Scalsol** [comment]
It is defined here https://github.com/Scalsol/RepPointsV2/blob/master/mmdet/models/dense_heads/reppoints_v2_head.py#L334 from L334-354.

**Comment by gp12345678** [comment]
@Scalsol 
Thanks!
