### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by RocketFlash** [Scalsol/RepPointsV2#9]
Hi @Scalsol ! Thank you for amazing work!
I get this error when I start training:

`File "/root/workdir/RepPointsV2/mmdet/apis/train.py", line 100, in train_detector`
`optimizer_config = OptimizerHook(**cfg.optimizer_config)`
`TypeError: __init__() got an unexpected keyword argument '_delete_'`

**Comment by Scalsol** [comment]
What's your mmcv's version? The `__delete__` attribute is available after v0.4.0

**Comment by RocketFlash** [comment]
@Scalsol I modified config for my dataset and reason of this error was in parameters order in config file. I fixed it. Now I have another error:

`if input.dim() == 3 and mode == 'nearest':`
`AttributeError: 'NoneType' object has no attribute 'dim'`

**Comment by Scalsol** [comment]
Please give a detailed description of your error (e.g. in which line of which file with what command the error occurs), then I could help fix the problem :)

**Comment by RocketFlash** [comment]
Sorry, another question: Is it possible to train the model without masks?

**Comment by Scalsol** [comment]
Yes, RepPoints V1 and V2 only requires bounding box annotations.

**Comment by RocketFlash** [comment]
I found the problem, I didn't put 'gt_sem_map' and 'gt_sem_weights' in
`dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_sem_map', 'gt_sem_weights']),` , and because of this an error occured in my custom augmentation pipeline.
Now the model has started training:)

**Comment by shanggdlk** [comment]
> Hi @Scalsol ! Thank you for amazing work!
> I get this error when I start training:
> 
> `File "/root/workdir/RepPointsV2/mmdet/apis/train.py", line 100, in train_detector`
> `optimizer_config = OptimizerHook(**cfg.optimizer_config)`
> `TypeError: __init__() got an unexpected keyword argument '_delete_'`

Hi, dude, I saw a similar error, can you tell me how you fix it?

Thanks!
